// File generated by hand from android/app/google-services.json and
// ios/Runner/GoogleService-Info.plist (Firebase project "ts-mincab") —
// equivalent to what `flutterfire configure` would produce. Regenerate with
// that command instead of editing by hand if the Firebase project changes.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run `flutterfire configure` to add a web app if push notifications '
        'are ever needed there too.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd8sT39WeWiGWBctnuFQ1ebKQX8XXNacY',
    appId: '1:873160171304:android:52dc755fcfe014a46ffa1d',
    messagingSenderId: '873160171304',
    projectId: 'ts-mincab',
    storageBucket: 'ts-mincab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-seEUsByrHiZgSaARFYWMFGzUDHj104',
    appId: '1:873160171304:ios:c1fae2d29be4f7b56ffa1d',
    messagingSenderId: '873160171304',
    projectId: 'ts-mincab',
    storageBucket: 'ts-mincab.firebasestorage.app',
    iosBundleId: 'com.tsminicab.dispatch',
  );
}
